export const weatherIcon = {
  blizzerd: require("./blizzerd.png"),
  blowingSnow: require("./blowing-snow.png"),
  clearNight: require("./clear-night.png"),
  cloudyClearNight: require("./cloudy-clear-night.png"),
  cloudyClear: require("./cloudy-clear.png"),
  cloudy: require("./cloudy.png"),
  drizzleNight: require("./drizzle-night.png"),
  drizzleSun: require("./drizzle-sun.png"),
  drizzle: require("./drizzle.png"),
  fog: require("./fog.png"),
  hail: require("./hail.png"),
  heavyRain: require("./heavy-rain.png"),
  partlyCloudyNight: require("./partly-cloudy-night.png"),
  partlyCloudy: require("./partly-cloudy.png"),
  rainNight: require("./rain-night.png"),
  rainSun: require("./rain-sun.png"),
  rainThunderstorm: require("./rain-thunderstorm.png"),
  rain: require("./rain.png"),
  scatteradShowersNight: require("./scatterad-showers-night.png"),
  scatterdShowers: require("./scatterd-showers.png"),
  scatterdThunderstorm: require("./scatterd-thunderstorm.png"),
  severThunderstorm: require("./sever-thunderstorm.png"),
  sleet: require("./sleet.png"),
  snow: require("./snow.png"),
  sunny: require("./sunny.png"),
  wind: require("./wind.png"),
} as const

export const icon = {
  location: require("./location-icon.png"),
  date: require("./date-icon.png"),
  humidity: require("./humidity.png"),
  outline: require("./outline.png"),
} as const